added function sortStrings
js-tasks-ru/js-20201211_vktr-gldk10-98 pull request #2
Opened 2020-12-17 20:45 UTC by GladkaV

2020-12-17 21:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
- should return new object with one passed field
- should return new object with a few passed field
- should return an empty object if passed fields does not found
```

2020-12-17 23:14 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    if (param === 'desc') return newArray.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2020-12-17 23:14 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-12-17 23:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
- should return new object with one passed field
- should return new object with a few passed field
- should return an empty object if passed fields does not found
```

2020-12-18 17:27 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-19 22:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-20 13:22 UTC, dosandk approved these changes

2020-12-20 13:22 UTC, merged